# Generated by Django 5.2.17 on 2026-08-09 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="CSS класс иконки (например, bi-film)",
                        max_length=50,
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "original_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Оригинальное название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "year",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Год выпуска"),
                ),
                (
                    "poster",
                    models.ImageField(blank=True, upload_to="posters/", verbose_name="Постер"),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID из внешних API (Kinopoisk, TMDB и т.д.)",
                        max_length=100,
                        verbose_name="Внешний ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительные данные в формате JSON",
                        verbose_name="Метаданные",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент контента",
                "verbose_name_plural": "Элементы контента",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "title"], name="content_con_categor_05b946_idx"
                    ),
                    models.Index(fields=["external_id"], name="content_con_externa_c26090_idx"),
                ],
            },
        ),
    ]
