# Generated by Django 5.2.17 on 2026-08-11 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Неактивные объекты скрыты из каталога (мягкое удаление)', verbose_name='Активен'),
        ),
        migrations.CreateModel(
            name='UserContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', models.TextField(blank=True, verbose_name='Личный комментарий')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='content.contentitem', verbose_name='Элемент контента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Объект пользователя',
                'verbose_name_plural': 'Объекты пользователей',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_item'), name='unique_user_content_item')],
            },
        ),
    ]
