# Generated by Django 5.2.17 on 2026-08-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_contentitem_is_active_usercontentitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="contentitem",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="content.genre", verbose_name="Жанры"
            ),
        ),
    ]
