# Generated by Django 5.2.17 on 2026-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_migrate_genres_from_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontentitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "В планах"),
                    ("watching", "Смотрю"),
                    ("on_hold", "Отложил"),
                    ("completed", "Посмотрел"),
                ],
                default="planned",
                max_length=20,
                verbose_name="Статус просмотра",
            ),
        ),
    ]
