# Generated by Django 5.2.17 on 2026-08-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_usercontentitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="external_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Рейтинг из внешних источников (Кинопоиск, TMDB)",
                max_digits=3,
                null=True,
                verbose_name="Внешний рейтинг",
            ),
        ),
    ]
