# Generated by Django 5.2.17 on 2026-08-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_migrate_rating_from_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontentitem",
            name="personal_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                help_text="Оценка от 1 до 5 звёзд",
                null=True,
                verbose_name="Личная оценка",
            ),
        ),
    ]
