# Generated by Django 5.2.17 on 2026-08-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_usercontentitem_personal_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontentitem",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Публичные комментарии видны всем на главной странице",
                verbose_name="Публичный",
            ),
        ),
        migrations.AlterField(
            model_name="usercontentitem",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
    ]
