# Generated by Django 5.2.17 on 2026-08-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_usercontentitem_is_public_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID из внешних API (Kinopoisk и т.д.)",
                        max_length=100,
                        verbose_name="Внешний ID",
                    ),
                ),
                (
                    "photo",
                    models.URLField(
                        blank=True, help_text="URL фотографии персоны", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "Персона",
                "verbose_name_plural": "Персоны",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentItemPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("director", "Режиссёр"),
                            ("actor", "Актёр"),
                            ("artist", "Исполнитель"),
                            ("band_member", "Участник группы"),
                            ("composer", "Композитор"),
                            ("producer", "Продюсер"),
                            ("writer", "Сценарист"),
                        ],
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to="content.contentitem",
                        verbose_name="Элемент контента",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to="content.person",
                        verbose_name="Персона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персона контента",
                "verbose_name_plural": "Персоны контента",
                "ordering": ["role", "person__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_item", "person", "role"),
                        name="unique_content_item_person_role",
                    )
                ],
            },
        ),
    ]
