# Generated by Django 5.2.17 on 2026-08-14 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_person_contentitemperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Например, сериал для сезона",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="content.contentitem",
                verbose_name="Родительский объект",
            ),
        ),
    ]
