# Generated by Django 5.2.17 on 2026-08-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_category_options_category_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontentitem',
            name='personal_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Оценка от 1 до 10', null=True, verbose_name='Личная оценка'),
        ),
    ]
