# Generated by Django 5.2.17 on 2026-08-09 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("groups", "0002_initial"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="content_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="content.contentitem",
                verbose_name="Элемент контента",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Группа, в контексте которой оставлен отзыв",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="groups.group",
                verbose_name="Группа",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reviews.review",
                verbose_name="Отзыв",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["content_item", "group"], name="reviews_rev_content_9eb673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "created_at"], name="reviews_rev_user_id_35ef9b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "content_item", "group")},
        ),
    ]
