# Generated by Django 5.2.17 on 2026-08-13 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0003_groupinvitation_groupmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("group_invite", "Приглашение в группу"),
                            ("group_invite_accepted", "Приглашение принято"),
                            ("group_invite_declined", "Приглашение отклонено"),
                            ("group_new_message", "Новое сообщение в группе"),
                        ],
                        max_length=30,
                        verbose_name="Тип уведомления",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("message", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="URL, куда ведёт клик по уведомлению",
                        max_length=500,
                        verbose_name="Ссылка",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Прочитано")),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="groups.groupinvitation",
                        verbose_name="Приглашение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read"], name="notificatio_user_id_427e4b_idx")
                ],
            },
        ),
    ]
