# Generated by Django 5.2.17 on 2026-09-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('group_invite', 'Приглашение в группу'), ('group_invite_accepted', 'Приглашение принято'), ('group_invite_declined', 'Приглашение отклонено'), ('group_new_message', 'Новое сообщение в группе'), ('new_episode', 'Новая серия'), ('new_season', 'Новый сезон')], max_length=30, verbose_name='Тип уведомления'),
        ),
    ]
